import { CampusEvent } from "./supabase/types";

const now = Date.now();
const minutes = (n: number) => n * 60 * 1000;

export const MOCK_EVENTS: CampusEvent[] = [
  {
    id: "mock-1",
    title: "5-a-side Football — need 2 players",
    type: "sports",
    location: "Sports Complex, Ground 2",
    postedBy: "Sports Dept",
    startTime: new Date(now - minutes(15)).toISOString(),
    expiresAt: new Date(now + minutes(40)).toISOString(),
    description: "Casual match, all departments welcome. Bring your own boots.",
    sportKind: "football",
    imageUrl: null,
    createdAt: new Date(now - minutes(15)).toISOString(),
  },
  {
    id: "mock-2",
    title: "ACM Society — Live Coding Battle",
    type: "society",
    location: "CS Auditorium",
    postedBy: "ACM COMSATS",
    startTime: new Date(now - minutes(5)).toISOString(),
    expiresAt: new Date(now + minutes(85)).toISOString(),
    description: "Real-time competitive programming, spectators welcome.",
    sportKind: null,
    imageUrl: null,
    createdAt: new Date(now - minutes(5)).toISOString(),
  },
  {
    id: "mock-3",
    title: "Table Tennis Open Table",
    type: "sports",
    location: "Rec Room, Block 5",
    postedBy: "Sports Dept",
    startTime: new Date(now + minutes(90)).toISOString(),
    expiresAt: new Date(now + minutes(150)).toISOString(),
    description: null,
    sportKind: "tennis",
    imageUrl: null,
    createdAt: new Date(now - minutes(2)).toISOString(),
  },
  {
    id: "mock-4",
    title: "Photography Society — Golden Hour Walk",
    type: "society",
    location: "Main Lawn, meet at flagpole",
    postedBy: "Lens & Light",
    startTime: new Date(now + minutes(180)).toISOString(),
    expiresAt: new Date(now + minutes(240)).toISOString(),
    description: "Bring any camera — phones count. We'll walk the perimeter.",
    sportKind: null,
    imageUrl: null,
    createdAt: new Date(now - minutes(1)).toISOString(),
  },
  {
    id: "mock-5",
    title: "Cricket Trials — Inter-dept League",
    type: "sports",
    location: "Cricket Ground",
    postedBy: "Sports Dept",
    startTime: new Date(now + minutes(60 * 24)).toISOString(),
    expiresAt: new Date(now + minutes(60 * 26)).toISOString(),
    description: "Open trials for the spring inter-department league.",
    sportKind: "cricket",
    imageUrl: null,
    createdAt: new Date(now).toISOString(),
  },
  {
    id: "mock-6",
    title: "Debating Society — Parliamentary Finals",
    type: "society",
    location: "Auditorium A",
    postedBy: "COMSATS Debating Society",
    startTime: new Date(now + minutes(60 * 26)).toISOString(),
    expiresAt: new Date(now + minutes(60 * 28)).toISOString(),
    description: "Grand finale — open seating, doors at 5.",
    sportKind: null,
    imageUrl: null,
    createdAt: new Date(now).toISOString(),
  },
];
